<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartRfqFlow.Application\SmartRfqFlow.Application.csproj" />
    <ProjectReference Include="..\SmartRfqFlow.Infrastructure\SmartRfqFlow.Infrastructure.csproj" />
  </ItemGroup>

</Project>
